Select FIRST_NAME AS WORKER_NAME from Worker; 
Select upper(FIRST_NAME) from Worker; 
Select distinct DEPARTMENT from Worker; 
Select substring(FIRST_NAME,1,3) from Worker; 
select instr(BINARY FIRST_NAME,'a') from worker where FIRST_NAME = 'Amitabh';
Select RTRIM(FIRST_NAME) from Worker; 
Select LTRIM(DEPARTMENT) from Worker; 
Select distinct length(DEPARTMENT) from Worker; 
Select REPLACE(FIRST_NAME,'a','A') from Worker;
Select CONCAT(FIRST_NAME, ' ', LAST_NAME) AS 'COMPLETE_NAME' from Worker; 
Select * from Worker order by FIRST_NAME asc; 
Select * from Worker order by FIRST_NAME asc,DEPARTMENT desc; 
Select * from Worker where FIRST_NAME in ('Vipul','Satish'); 
Select * from Worker where FIRST_NAME not in ('Vipul','Satish'); 
Select * from Worker where DEPARTMENT like 'Admin%'; 
Select * from Worker where FIRST_NAME like '%a%'; 
Select * from Worker where FIRST_NAME like '%a'; 
select * from worker where FIRST_NAME like '%_____h';
Select * from Worker where SALARY between 100000 and 500000; 
Select * from Worker where year(JOINING_DATE) = 2014 and month(JOINING_DATE) = 2; 